### PR TITLE
[!!!][TASK] Lock provider type in template artifact

### PR DESCRIPTION
**Pull request by eliashaeussler**
Restoring a build artifact cannot be done properly if the original template provider cannot be determined. Hence, we now use the provider *type* instead of its *name*.

This is breaking change as it results in a new build artifact version (`1679497137` → `1688738958`).

### CODE REVIEW

**Comment by mteu** [comment]
This seems ready for shipment. What could possibly be open here?

**Comment by eliashaeussler** [comment]
> This seems ready for shipment. What could possibly be open here?

@mteu Once #96 is merged, I'll change this PR to lock the provider *type* instead of *class*. That's a little bit more straightforward in terms of artifact reconstitution.

**Comment by mteu** [comment]
> > This seems ready for shipment. What could possibly be open here?
> 
> @mteu Once #96 is merged, I'll change this PR to lock the provider _type_ instead of _class_. That's a little bit more straightforward in terms of artifact reconstitution.

Makes sense, thank you.

**Review by mteu — APPROVED** [review]

**Comment by mteu** [comment]
@eliashaeussler 👍

Wanna wait for codeclimate or fire at once?

**Comment by mteu** [comment]
👏

**Comment by eliashaeussler** [comment]
> @eliashaeussler 👍
> 
> Wanna wait for codeclimate or fire at once?

Thanks for your approval. I'm too tired to wait for all those obviously unstable CGL tools.

**Comment by mteu** [comment]
> Thanks for your approval. I'm too tired to wait for all those obviously unstable CGL tools.

I feel you.

**Pull request merged**
