### PR TITLE
[FEATURE] Set Packagist as default provider and auto-fetch template sources

### PR DESCRIPTION
**Pull request by mteu**
## Major Changes
This PR addresses the second part of the https://github.com/CPS-IT/project-builder/issues/57 where a default template source provider (in this case Packagist) is now selected. Packages are automatically fetched from this provider and are suggested to the user. This will allow first-time users to quickly get started. More experienced users are still given the opportunity to define a custom registry (and with #53 a VCS provider).

## Minor Changes

- The status information (when fetching packages from a provider) is now showing the URL making it a bit cleary to users where the project builder attempts to fetch template packages from.

### CODE REVIEW

**Review by eliashaeussler — COMMENTED** [review]
Thanks! I'll try to add some test cases for the bootstrapping part.

**Comment by eliashaeussler** [comment]
@mteu I addressed the potential failure in cases where no packages are available on Packagist in b65e268. Can you please have a look at it?

**Comment by eliashaeussler** [comment]
I'll add some test cases once #65 is merged.

**Comment by mteu** [comment]
@eliashaeussler The issue with the "cached" repository will only arise with this PR #60, since we're not prompting a custom repository in the stable version so far. As a result I would keep the bugfix in this PR and will not open another issue referencing a the package version `dev-feature/elevate-packagist-provider-in-template-selection`.

**Comment by mteu** [comment]
> @mteu I addressed the potential failure in cases where no packages are available on Packagist in [b65e268](https://github.com/CPS-IT/project-builder/commit/b65e2687cdd00d1c299a6fd06058684be4c38618). Can you please have a look at it?

LGTM 👍 Thanks for spotting and fixing, @eliashaeussler 🚀

**Review by eliashaeussler — APPROVED** [review]
This looks good from my side now.

**Pull request merged**
