### PR TITLE
[!!!][TASK] Drop support for PHP 8.0 and migrate codebase to PHP 8.1

### PR DESCRIPTION
**Pull request by eliashaeussler**
PHP 8.0 is no longer actively supported. As we already support PHP 8.1 and 8.2, there's actually no more need to support PHP 8.0. Instead, we can move the codebase forward by migrating to PHP 8.1 and dropping PHP 8.0.

### CODE REVIEW

**Comment by eliashaeussler** [comment]
@mteu Once you're satisfied with these changes, I'll remove the required status checks for PHP 8.0.

**Comment by mteu** [comment]
> @mteu Once you're satisfied with these changes, I'll remove the required status checks for PHP 8.0.

Shouldn't take too long with only 90 files changed.

**Comment by eliashaeussler** [comment]
> Shouldn't take too long with only 90 files changed.

92, please.

**Review by mteu — APPROVED** [review]
💪 Milestone!

**Pull request merged**
