### PR TITLE
[FEATURE] Implement concept for artifact migration

### PR DESCRIPTION
**Pull request by eliashaeussler**
This PR implements aims to integrate a migration concept for versioned build artifacts.

> **Note** As this is an internal component, it currently does not need to be documented. However, once the relevant components for project migration (see #85) are implemented, we should add a small chapter explaining what is happening internally.

In this PR, three new components are added:

1. `Builder\ArtifactGenerator` now takes care of artifact generation. The artifacts available at `Builder\Artifact` were rewritten to exclude every business-logic, making them easily restorable when it comes to artifact reconstitution. That said, the main artifact is no longer `Builder\Artifact\BuildArtifact`, but `Builder\Artifact\Artifact` which contains all sub-artifacts, including `Builder\Artifact\BuilderArtifact` and friends. In addition, the `Builder\BuildResult` does no longer store a prepared artifact. Instead, it holds a reference to the artifact file being generated later. For this, two new methods `Builder\BuildResult::setArtifactFile()` and `Builder\BuildResult::getArtifactFile()` were added.
2. `Builder\Artifact\Migration\Migration` provides an interface for concrete artifact migrations. A class implementing this interface should provide the source artifact version, target artifact version and the concrete migration implementation. In addition, a `Builder\Artifact\Migration\BaseMigration` class is added which contains basic methods for usual artifact migrations.
3. `Builder\ArtifactReader` is a brand-new component that is added next to the version component. It reads an artifact from a given file, migrates it to the current version using all registered migrations and maps the migrated artifact to an instance of `Builder\Artifact\Artifact`. This way, it is possible to restore a dumped artifact and reuse it, e.g. when implementing project synchronization as requested in #85.

:bulb: In addition to the new components, a silent migration for all v1 artifacts is added: The `artifact.file` path is silently migrated to `artifact.path` within `Builder\Artifact\Migration\Migration1679497137`. That's because this path was wrong implemented in the first place and differed from the configured property in the build artifact JSON schema.

Resolves: #117

### CODE REVIEW

**Comment by mteu** [comment]
Oh boy.

**Comment by eliashaeussler** [comment]
The following issue needs to be resolved first in order to get this merged:

> Schema not found: file:///Users/e.haeussler/test/pb-preview/resources/build-artifact.schema.json#

⬆️ This error occurs at the end when dumping the artifact. It happens because the schema file is no longer available due to the previous file mirroring.

**Comment by eliashaeussler** [comment]
> 🚨 The following issue needs to be resolved first in order to get this merged:
> 
> > Schema not found: file:///Users/e.haeussler/test/pb-preview/resources/build-artifact.schema.json#
> 
> ⬆️ This error occurs at the end when dumping the artifact. It happens because the schema file is no longer available due to the previous file mirroring.

Done ✅

**Review by mteu — APPROVED** [review]
OMG. I literally cannot wait to see this in action. 🌸

**Pull request merged**
