### PR TITLE
[!!!][FEATURE] Introduce dynamic providers for template packages

### PR DESCRIPTION
**Pull request by eliashaeussler**
This PR introduces dynamic providers for template packages, decoupling the project builder from the internal Satis instance hosted at CPS.

Packages can now either be registered at Packagist.org or any other Composer registry (such as self-hosted Satis instances). The appropriate provider can be selected as first step within the project builder lifecycle.

Resolves: #11

### CODE REVIEW

**Review by mteu — COMMENTED** [review]
Hi @eliashaeussler,

Thanks for your magnificient pull request which I would most gladly approve. Your changes are a major step towards the opening up of the project builder to a broader audience. 💛 

I have but one suggestion myself: In terms of UX I would think we ought to keep in mind that there a plenty users that would love to dive right without consulting the documentation. I know that we should not enable such behavior. Yet, I'd still like to help those users, too.

How about we give a little more information as to what needs to be done before one can actually use builder? We could reference the corresponding documentation whenever a qualifying exception in thrown (e.g. in `InvalidTemplateSourceException`). That way we would not have to clutter the actual steps. What do you say?

Again, thanks for introducing custom providers! 🚀

**Comment by eliashaeussler** [comment]
@mteu Thanks for your review and the valuable feedback.

Is the following approach something you'd consider helpful?

image

**Comment by mteu** [comment]
Thanks for taking the time, Elias. Yes, I'm sure this could help and is at the same time not too much of useless information for experience project-builder users. 🙇 
 
> Is the following approach something you'd consider helpful?

**Comment by eliashaeussler** [comment]
@mteu I added c09f40e which lets the user select the template source a second time if it fails in the first run.

**Comment by mteu** [comment]
Good idea, thanks.

**Comment by eliashaeussler** [comment]
@mteu I added some more test cases covering the updated template source selection process in `IO\Messenger`. Please have a look at it. Once you're satisfied, this PR is ready for merge.

**Comment by mteu** [comment]
> @mteu I added some more test cases covering the updated template source selection process in `IO\Messenger`. Please have a look at it. Once you're satisfied, this PR is ready for merge.

I'm blissfully content with the restored coverage. Thanks, @eliashaeussler.

**Pull request merged**
