### PR TITLE
[!!!][FEATURE] Introduce `project:create` console command

### PR DESCRIPTION
**Pull request by eliashaeussler**
With this PR, the project creation logic is extracted into a separate console command. The command is exposed to the Composer application, allowing to execute it through Composer as `composer project:create`. In order to make this change possible, the package is converted to a Composer plugin.

This has no impact on the previous single use case – `composer create-project`. Instead, it provides a better abstraction of the project creation logic and allows to execute the project creation with having the project builder as (dev) dependency.

This also paves the way for an implementation of #85.

ToDo:

- [x] Documentation
- [x] Tests

### CODE REVIEW

**Comment by eliashaeussler** [comment]
@mteu This PR is now ready for review.

**Comment by mteu** [comment]
Thanks, I'll see to it.

**Comment by eliashaeussler** [comment]
@mteu ping

**Review by mteu — APPROVED** [review]
💛

**Pull request merged**
